Module2 task1
htmlacademy-adaptive/2302197-sedona-28 pull request #2
Opened 2023-04-03 21:18 UTC by Developer2220

2023-04-03 22:16 UTC, uzinok reviewed
не все страницы сделаны, странные названия у картинок, проверь заголовки

2023-04-03 22:16 UTC, uzinok commented on source/index.html
> +    <img src="source/img/back-mobile.jpg.jpg" width="901" height="389" alt="Вид на горы">
странное название картинки
не вижу эту картинку на макете

2023-04-03 22:16 UTC, uzinok commented on source/index.html
> +          <h3>СЕДОНА — небольшой городок в АРИЗОНЕ,
почему это заголовок?

2023-04-03 22:16 UTC, uzinok commented on source/index.html
> +      <button class="main-nav_toggle" type="button"></button>
кнопка без подписи

2023-04-03 22:16 UTC, uzinok commented on source/index.html
> +            зАСЛУЖИвающий большего!
почему буквы пляшут? причём во многих метсах

2023-04-03 22:16 UTC, uzinok commented on source/index.html
> +            <p class="advantages_description">СЕДОНА НЕ АТТРАКЦИОН ДЛЯ ТУРИСТОВ, ТАМ ТЕЧЕТ СВОЯ ЖИЗНЬ</p>
капсом писать нельзя

2023-04-03 22:16 UTC, uzinok commented on source/index.html
> +          <li class="advantages_item">
у нас пять приемуществ, соответственно должно быть пять элементов списка

2023-04-03 22:16 UTC, uzinok commented on source/index.html
> +            <img src="../2302197-sedona-28/source/img/photo-city.jpg" width="520" height="260" alt="Вид на город">
1. путь картинки не верный
2. не на своём месте картика

2023-04-03 22:16 UTC, uzinok commented on source/index.html
> +      <h2 class="subscription_title">Заинтересовались</h2>
это точно заголовок?

2023-04-03 22:16 UTC, uzinok commented on source/index.html
> +      <span class="main-footer_link">#visitSEDONA</span>
что такое хештег?

2023-04-03 22:16 UTC, uzinok commented on source/index.html
> +      <div class="main-footer_contacts">
для чего этот див?

2023-04-03 22:16 UTC, uzinok commented on source/index.html
> +              <path
кто так добавляет svg в разметку? студенты html 1!!!

2023-04-03 22:16 UTC, uzinok commented on source/index.html
> +          <b class="copyright_text">Разработано</b>
кем разработано?

2023-04-04 20:15 UTC, Developer2220 commented on source/index.html
> +    <img src="source/img/back-mobile.jpg.jpg" width="901" height="389" alt="Вид на горы">
Исправил

2023-04-04 20:19 UTC, Developer2220 commented on source/index.html
> +          <h3>СЕДОНА — небольшой городок в АРИЗОНЕ,
Сделал спаном

2023-04-04 20:22 UTC, Developer2220 commented on source/index.html
> +      <button class="main-nav_toggle" type="button"></button>
Добавил span c visually hidden

2023-04-04 20:28 UTC, Developer2220 commented on source/index.html
> +            зАСЛУЖИвающий большего!
Вероятно, из-за того что копировал с макета. Исправил

2023-04-04 20:29 UTC, Developer2220 commented on source/index.html
> +            <p class="advantages_description">СЕДОНА НЕ АТТРАКЦИОН ДЛЯ ТУРИСТОВ, ТАМ ТЕЧЕТ СВОЯ ЖИЗНЬ</p>
Исправил

2023-04-04 21:10 UTC, Developer2220 commented on source/index.html
> +          <li class="advantages_item">
сделали дивами и списком

2023-04-04 21:11 UTC, Developer2220 commented on source/index.html
> +            <img src="../2302197-sedona-28/source/img/photo-city.jpg" width="520" height="260" alt="Вид на город">
исправил

2023-04-04 21:13 UTC, Developer2220 commented on source/index.html
> +      <h2 class="subscription_title">Заинтересовались</h2>
сделал спаном и добавил скрытый заголовок

2023-04-04 21:16 UTC, Developer2220 commented on source/index.html
> +      <span class="main-footer_link">#visitSEDONA</span>
сделать ссылкой?

2023-04-04 21:22 UTC, Developer2220 commented on source/index.html
> +      <div class="main-footer_contacts">
Убрал

2023-04-04 21:27 UTC, Developer2220 commented on source/index.html
> +              <path
прописал путь

2023-04-04 21:28 UTC, Developer2220 commented on source/index.html
> +          <b class="copyright_text">Разработано</b>
далее прописал svg  alt = Html academy

2023-04-04 21:37 UTC, Developer2220 commented on source/index.html
> +          <b class="copyright_text">Разработано</b>
Не прошло по валидатору, видимо alt не разрешен. Тогда скрытым спаном допишу html academy

2023-04-08 11:21 UTC, uzinok reviewed
https://yoksel.github.io/html-tree/ бэм совсем грустный
в целом верстка хорошая, но будут переделки/подделки во время построения сеток и стилизации некоторых других элементов

2023-04-08 11:21 UTC, uzinok commented on source/catalog.html
> +              HTML ACADEMY
капсом не нужно писать в html

2023-04-08 11:21 UTC, uzinok commented on source/catalog.html
> +    <img src="../source/img/photo-mountains.jpg" width="520" height="260" alt="Вид на горы">
в разметке фоновое изображение, но нет контентного, пути прописаны не верно
https://dzen.ru/video/watch/63b2e50e7fc57c5d5d99ae89 в описании есть меню

2023-04-08 11:21 UTC, uzinok commented on source/index.html
> +        <div class="advantages_first">
логичнее использовать список, причем упорядоченный
об этом говорят даже номера причин
https://skr.sh/sJFZnkdXIYd

2023-04-08 11:21 UTC, uzinok commented on source/index.html
> +      <div class="main-footer_contacts">
не убрал

2023-04-08 11:21 UTC, uzinok commented on source/form.html
> +              <span class="field-impressions_mark"></span>
лучше без этих спанов

2023-04-08 11:21 UTC, uzinok commented on source/form.html
> +              <input class="visually-hidden field-impressions_input" type="checkbox" name="impressions"
тут точно checkbox? можно то выбрать только один из трех пунктов

2023-04-08 11:21 UTC, uzinok commented on source/form.html
> +      <button class="form_button" type="button">Отправить отзыв</button>
какой должен быть тип кнопки? форма у тебя вообще из-за этого не работает
и не забывай что с пустыми текстовыми полями форма не должна отправляться

2023-04-08 11:21 UTC, uzinok commented on source/catalog.html
> +        <svg class="expance_like"></svg>
если это не интерактивный элемент - не нужно svg вовсе добавлять в разметку
у цифр очепятка
и нет дополнительной подписи: непонятно чего 1350

2023-04-11 09:19 UTC, Kartaviy-arteom requested changes

2023-04-11 09:19 UTC, Kartaviy-arteom commented on source/img/htmlacademy.svg.svg
два раза формат указан (svg)

2023-04-11 09:19 UTC, Kartaviy-arteom commented on source/index.html
> +      <img src="../source/img/logotype.svg" width="185" height="96" alt="Седона">
тут ты указываешь относительный адрес от index.html (source у тебя в адресе не будет)

2023-04-11 09:19 UTC, Kartaviy-arteom commented on source/index.html
> +      <span class="visually-hidden">HTML Academy</span>
это пояснение внутри ссылки будет

2023-04-11 09:19 UTC, Kartaviy-arteom commented on source/index.html
> +              <img src="../source/img/photo-city.jpg" width="520" height="260" alt="Вид на город">
пути и далее везде подправить

2023-04-11 09:19 UTC, Kartaviy-arteom commented on source/catalog.html
> +        <span class="expance__number">1350</span>
тут будет кнопка чтобы "лайкнуть" понравившееся изображение

2023-04-12 12:52 UTC, Kartaviy-arteom approved these changes

2023-04-12 12:53 UTC, merged